// angular/src/app/feature/sales/invoices/invoices.component.ts
import { Component, computed } from "@angular/core";
import { RouterModule } from "@angular/router";
import { resource } from "../../../core/utilities/resource";
import { CommonModule } from "@angular/common";
import Navlink from "../../../core/component/navlink.component";
import { HoverPreloadStrategy } from "src/app/core/strategy/hover-strategy";
import { load } from "./invoices.component.server";

@Component({
    imports: [ CommonModule, RouterModule, Navlink ],
    providers: [ HoverPreloadStrategy ],
    standalone: true,
    selector: 'app-invoices',
    templateUrl: './invoices.component.html',
    styleUrl: './invoices.component.css',
})
export default class InvoicesComponent {
    readonly invoices = resource<typeof load>();

    shown = computed(() => {
        const i = { ...this.invoices() };

        i.value = i.value?.slice(0, 5);

        return i;
    });

    totalOverDue = computed(() => {
        const stateOfInvoices = this.invoices();

        if(stateOfInvoices.state !== 'idle') {
            return 0;
        }

        return stateOfInvoices.value.filter(i => i.status.status === 'overdue').reduce((t, i) => t + i.price.value, 0);
    });
}

<h1>Invoices</h1>

<header>
    @if(totalOverDue(); as overdue) {
        <span>overdue</span>
        <p>{{ overdue }}</p>
    }
</header>

<h2>Invoice list</h2>

<nav>
    @if(shown().value; as invoices) {
        @for (invoice of invoices; track invoice.id) {
            <a to="/sales/invoices/{{ invoice.id }}">
                <strong place>{{ invoice.place }}</strong>
                <strong price>{{ invoice.price.value | currency: invoice.price.currency }}</strong>
                <span year>{{ invoice.due.getFullYear() }}</span>
                @if (invoice.status; as due) {
                    <span [attr.due]="due.status">
                        @switch(due.status) {
                            @case ('paid') {
                                paid
                            }

                            @case ('overdue') {
                                overdue
                            }
    
                            @case ('dueToday') {
                                due today
                            }
    
                            @case ('dueInDays') {
                                due in {{due.dueInDays}} days
                            }
    
                            @case ('dueInYears') {
                                due in {{due.dueInYears}} years
                            }
                        }
                    </span>
                }
            </a>
        }
    } 
    @else if (invoices().state === 'loading') {
        <span>Loading...</span>
    }
</nav>

<main>
    <router-outlet></router-outlet>
</main>

// solid-start/src/routes/(shell)/sales/invoices.tsx
import { RouteSectionProps, cache, createAsync, A } from "@solidjs/router";
import styles from './invoices.module.css';
import { createMemo, For, Match, Switch } from "solid-js";
import { list } from "~/services/invoices";

const getInvoices = cache(list, 'invoices');

export const route = {
    load: () => createAsync(() => getInvoices()),
};

export default function Invoices({ children, data }: RouteSectionProps<ReturnType<typeof route['load']>>) {
    const invoices = data!;

    const shown = createMemo(() => {
        return invoices()?.slice(0, 5) ?? [];
    });

    const totalOverDue = createMemo(() => {
        return invoices()?.filter(i => i.status.status === 'overdue').reduce((t, i) => t + i.price.value, 0) ?? 0;
    });

    return <div class={styles.host}>
        <h2>Total due</h2>

        <header>
            <span>overdue</span>
            <p>{totalOverDue()}</p>

            <A href="/sales/invoices/new" >Add new invoice</A>
        </header>

        <h3>Invoices</h3>

        <nav>
            <For each={shown()}>
                {i => <A href={`/sales/invoices/${i.id}`} end>
                    <strong place>{i.place}</strong>
                    <strong price>{i.price.value}</strong>
                    <span year>{i.due.getFullYear()}</span>
                    <span due={i.status.status}>
                        <Switch>
                            <Match when={i.status.status === 'paid' && i.status}>
                                paid
                            </Match>

                            <Match when={i.status.status === 'overdue' && i.status}>
                                overdue
                            </Match>

                            <Match when={i.status.status === 'dueToday' && i.status}>
                                due today
                            </Match>

                            <Match when={i.status.status === 'dueInDays' && i.status}>
                                {(due) => <>due in {due().dueInDays} days</>}
                            </Match>

                            <Match when={i.status.status === 'dueInYears' && i.status}>
                                {(due) => <>due in {due().dueInYears} days</>}
                            </Match>
                        </Switch>
                    </span>
                </A>}
            </For>
        </nav>

        <main>
            {children}
        </main>
    </div>;
}
