// angular/src/app/feature/sales/invoices/invoices.component.ts
import { Component, computed } from "@angular/core";
import { RouterModule } from "@angular/router";
import { resource } from "../../../core/utilities/resource";
import { CommonModule } from "@angular/common";
import Navlink from "../../../core/component/navlink.component";
import { HoverPreloadStrategy } from "src/app/core/strategy/hover-strategy";
import { load } from "./invoices.component.server";

@Component({
    imports: [ CommonModule, RouterModule, Navlink ],
    providers: [ HoverPreloadStrategy ],
    standalone: true,
    selector: 'app-invoices',
    templateUrl: './invoices.component.html',
    styleUrl: './invoices.component.css',
})
export default class InvoicesComponent {
    readonly invoices = resource<typeof load>();

    shown = computed(() => {
        const i = { ...this.invoices() };

        i.value = i.value?.slice(0, 5);

        return i;
    });

    totalOverDue = computed(() => {
        const stateOfInvoices = this.invoices();

        if(stateOfInvoices.state !== 'idle') {
            return 0;
        }

        return stateOfInvoices.value.filter(i => i.status.status === 'overdue').reduce((t, i) => t + i.price.value, 0);
    });
}

<h1>Invoices</h1>

<header>
    @if(totalOverDue(); as overdue) {
        <span>overdue</span>
        <p>{{ overdue }}</p>
    }
</header>

<h2>Invoice list</h2>

<nav>
    @if(shown().value; as invoices) {
        @for (invoice of invoices; track invoice.id) {
            <a to="/sales/invoices/{{ invoice.id }}">
                <strong place>{{ invoice.place }}</strong>
                <strong price>{{ invoice.price.value | currency: invoice.price.currency }}</strong>
                <span year>{{ invoice.due.getFullYear() }}</span>
                @if (invoice.status; as due) {
                    <span [attr.due]="due.status">
                        @switch(due.status) {
                            @case ('paid') {
                                paid
                            }

                            @case ('overdue') {
                                overdue
                            }
    
                            @case ('dueToday') {
                                due today
                            }
    
                            @case ('dueInDays') {
                                due in {{due.dueInDays}} days
                            }
    
                            @case ('dueInYears') {
                                due in {{due.dueInYears}} years
                            }
                        }
                    </span>
                }
            </a>
        }
    } 
    @else if (invoices().state === 'loading') {
        <span>Loading...</span>
    }
</nav>

<main>
    <router-outlet></router-outlet>
</main>

// solid-start/src/routes/admin/sales/invoices.tsx
import { RouteSectionProps, cache, createAsync, A, RouteDefinition } from '@solidjs/router';
import { createMemo, For, Match, Switch } from 'solid-js';
import { useI18n } from '~/i18n.context';
import { list } from '~/services/invoices';

const getInvoices = cache(list, 'invoices');

export const route = {
    load: () => createAsync(() => getInvoices()),
} satisfies RouteDefinition;

export default function Invoices(props: RouteSectionProps<ReturnType<(typeof route)['load']>>) {
    const invoices = props.data!;

    const { t } = useI18n();

    const shown = createMemo(() => {
        return invoices()?.slice(0, 5) ?? [];
    });

    const totalOverDue = createMemo(() => {
        return (
            invoices()
                ?.filter((i) => i.status.status === 'overdue')
                .reduce((t, i) => t + i.price.value, 0) ?? 0
        );
    });

    return (
        <div class="grid grid-rows-[auto_auto_1fr] grid-cols-[20em_1fr]">
            <h2 class="col-span-2">Total due</h2>

            <header class="col-span-2">
                <span>overdue</span>
                <p>{totalOverDue()}</p>

                <A href="/admin/sales/invoices/new">Add new invoice</A>
            </header>

            <h3 class="col-span-2">Invoices</h3>

            <nav class="grid grid-flow-row justify-start grid-cols-[100%] w-full border-2 border-neutral-200 rounded-l py-4 gap-y-3">
                <For each={shown()}>
                    {(i) => (
                        <A
                            class="grid grid-rows-2 grid-cols-2 p-4 gap-2 [&.active]:bg-neutral-200 [&.active]:font-bold"
                            href={`/admin/sales/invoices/${i.id}`}
                            end
                        >
                            <strong>{i.place}</strong>
                            <strong class="justify-self-end">{t('price', i.price.value, i.price.currency)}</strong>
                            <span>{i.due.getFullYear()}</span>
                            <span
                                class={`justify-self-end uppercase ${
                                    { paid: 'text-green-500', overdue: 'text-red-500' }[i.status.status] ?? ''
                                }`}
                            >
                                <Switch>
                                    <Match when={i.status.status === 'paid' && i.status}>paid</Match>

                                    <Match when={i.status.status === 'overdue' && i.status}>overdue</Match>

                                    <Match when={i.status.status === 'dueToday' && i.status}>due today</Match>

                                    <Match when={i.status.status === 'dueInDays' && i.status}>
                                        {(due) => <>due in {due().dueInDays} days</>}
                                    </Match>

                                    <Match when={i.status.status === 'dueInYears' && i.status}>
                                        {(due) => <>due in {due().dueInYears} days</>}
                                    </Match>
                                </Switch>
                            </span>
                        </A>
                    )}
                </For>
            </nav>

            <main class="grid grid-flow-col justify-start border-2 border-neutral-200 border-l-0 rounded-r p-4">
                {props.children}
            </main>
        </div>
    );
}
